import test from 'node:test';
import assert from 'node:assert/strict';
import { simulateLongRun, chooseVideoPokerHolds } from '../lib/realityEngine/longRun';

test('10,000 slot runs reconcile exactly',()=>{
  const result=simulateLongRun({gameType:'slots',stakeCents:500,seed:42});
  assert.equal(result.runs,10_000);
  assert.equal(result.wins+result.losses+result.pushes,10_000);
  assert.equal(result.totalReturnedCents-result.totalStakedCents,result.netCents);
  assert.ok(result.samples.length>0);
});

test('roulette long run uses the selected color and exact 37-pocket engine',()=>{
  const result=simulateLongRun({gameType:'casino',stakeCents:100,decision:'Black',seed:7});
  assert.equal(result.runs,10_000);
  assert.equal(result.totalStakedCents,1_000_000);
  assert.equal(result.wins+result.losses+result.pushes,10_000);
});

test('scratch long run reports near misses generated by the scratch engine',()=>{
  const result=simulateLongRun({gameType:'lottery',stakeCents:200,seed:99});
  assert.equal(result.runs,10_000);
  assert.ok(result.nearMisses>0);
});

test('sports long run uses displayed market selection',()=>{
  const result=simulateLongRun({gameType:'sports',stakeCents:1000,decision:'North Harbor',seed:17});
  assert.equal(result.runs,10_000);
  assert.ok(result.wins>0);
  assert.ok(result.losses>0);
});

test('video poker long run uses a fixed hold strategy, not random replacement',()=>{
  const holds=chooseVideoPokerHolds(['QS','QH','3D','6C','9S']);
  assert.deepEqual(holds,[true,true,false,false,false]);

  const result=simulateLongRun({gameType:'poker',stakeCents:500,seed:81});
  assert.equal(result.runs,10_000);
  assert.equal(result.wins+result.losses+result.pushes,10_000);
});
